package GUI;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

public class DashboardGUI extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DashboardGUI.class.getName());
    private ArrayList<SystemData.TemperatureSensor> sensorList = new ArrayList<>();
    private Timer simulationTimer;
    private DefaultTableModel tableModel;
    private boolean isEditMode = false;
    private int rowToEdit = -1;

        public DashboardGUI() {
                initComponents(); // <--- LEAVE THIS ALONE (It loads your Design)
                getContentPane().setBackground(new java.awt.Color(64,192,192));

                // ==========================================
                // NEW: THE MASTER SCROLL PANE TRICK
                // ==========================================
                // 1. Grab the completely finished GUI that NetBeans just built
                java.awt.Container originalLayout = getContentPane();

                // 2. Wrap the entire thing inside a brand new Scroll Pane
                javax.swing.JScrollPane masterScroll = new javax.swing.JScrollPane(originalLayout);

                // 3. Make the mouse-wheel scroll speed smooth (default is very slow)
                masterScroll.getVerticalScrollBar().setUnitIncrement(16); 
                masterScroll.setBorder(null); // Remove ugly double borders

                // 4. Set this new Scroll Pane as the main window display
                setContentPane(masterScroll);
                // ==========================================

                initCustomLogic(); // <--- LEAVE THIS ALONE (It loads the Brain)
            }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
        @SuppressWarnings("unchecked")
            // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
            private void initComponents() {

                pnl1 = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                txtUserID = new javax.swing.JTextField();
                txtToken = new javax.swing.JTextField();
                pnl3 = new javax.swing.JPanel();
                jLabel4 = new javax.swing.JLabel();
                jLabel3 = new javax.swing.JLabel();
                txtLocation = new javax.swing.JTextField();
                txtRoom = new javax.swing.JTextField();
                jLabel5 = new javax.swing.JLabel();
                txtSensorID = new javax.swing.JTextField();
                jLabel6 = new javax.swing.JLabel();
                tbtnEditSave = new javax.swing.JToggleButton();
                btnAdd = new javax.swing.JButton();
                btnDelete = new javax.swing.JButton();
                btnClear = new javax.swing.JButton();
                cmbSensorModel = new javax.swing.JComboBox<>();
                tbtnStartStop = new javax.swing.JToggleButton(); 
                sp1 = new javax.swing.JScrollPane();
                tbl1 = new javax.swing.JTable();
                sp2 = new javax.swing.JScrollPane();
                txtSerialMonitor = new javax.swing.JTextArea();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setTitle("Smart Room Temperature Monitoring System");
                setBackground(new java.awt.Color(10, 100, 100));
                setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
                setForeground(new java.awt.Color(31, 63, 127));
                setPreferredSize(new java.awt.Dimension(1200, 500)); 
                setSize(new java.awt.Dimension(1200, 500));

                pnl1.setBackground(new java.awt.Color(225, 255, 255));
                pnl1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "IoT Gateaway", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

                jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                jLabel1.setText("API Keys :");

                jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                jLabel2.setText("Telegram ID :");

                txtUserID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                txtUserID.setText("Insert User ID (Get User ID from IDBot)");
                txtUserID.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        txtUserIDActionPerformed(evt);
                    }
                });

                txtToken.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                txtToken.setText("Insert Chat Bot Token Keys (Get Token from BotFather)");

                javax.swing.GroupLayout pnl1Layout = new javax.swing.GroupLayout(pnl1);
                pnl1.setLayout(pnl1Layout);
                pnl1Layout.setHorizontalGroup(
                    pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                        .addGap(20, 20, 20) // Increased horizontal gap
                        .addGroup(pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUserID)
                            .addComponent(txtToken, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())
                );
                pnl1Layout.setVerticalGroup(
                    pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl1Layout.createSequentialGroup()
                        .addContainerGap(10, Short.MAX_VALUE)
                        .addGroup(pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUserID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10) // Strict 10px vertical gap
                        .addGroup(pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtToken, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10))
                );

                pnl3.setBackground(new java.awt.Color(225, 255, 255));
                pnl3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sensor Configuration", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

                jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                jLabel4.setText("Room :");

                jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                jLabel3.setText("Location :");

                txtLocation.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                txtLocation.setText("(e.g. FKTEN Block 8)");

                txtRoom.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                txtRoom.setText("(e.g. Computer Lab)");

                jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                jLabel5.setText("Sensor ID :");

                txtSensorID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                txtSensorID.setText("(e.g TS-000)");

                jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                jLabel6.setText("Sensor Model :");

                tbtnEditSave.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                tbtnEditSave.setText("Edit");
                tbtnEditSave.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        tbtnEditSaveActionPerformed(evt);
                    }
                });

                btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                btnAdd.setText("Add");
                btnAdd.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        btnAddActionPerformed(evt);
                    }
                });

                btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                btnDelete.setText("Delete");
                btnDelete.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        btnDeleteActionPerformed(evt);
                    }
                });

                btnClear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                btnClear.setText("Clear");
                btnClear.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        btnClearActionPerformed(evt);
                    }
                });

                cmbSensorModel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                cmbSensorModel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Unspecified", "DHT11", "DHT22", "BMP280", "BME280", "LM35" }));

                tbtnStartStop.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                tbtnStartStop.setText("START SYSTEM");
                tbtnStartStop.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        tbtnStartStopActionPerformed(evt);
                    }
                });

                javax.swing.GroupLayout pnl3Layout = new javax.swing.GroupLayout(pnl3);
                pnl3.setLayout(pnl3Layout);
                pnl3Layout.setHorizontalGroup(
                    pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl3Layout.createSequentialGroup()
                        .addContainerGap(20, 20)
                        .addGroup(pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(20, 20, 20) // Wider horizontal gap
                        .addGroup(pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSensorID, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbSensorModel, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40) // Wider gap before buttons
                        .addGroup(pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbtnEditSave, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40) // Gap before Big Button
                        .addComponent(tbtnStartStop, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                pnl3Layout.setVerticalGroup(
                    pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbtnEditSave, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10) // Strict 10px vertical gap
                        .addGroup(pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl3Layout.createSequentialGroup()
                                .addGroup(pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10) // Strict 10px vertical gap
                                .addGroup(pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSensorID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(tbtnStartStop, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)) // 70px perfectly spans 2 fields + 10px gap!
                        .addGap(10, 10, 10) // Strict 10px vertical gap
                        .addGroup(pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbSensorModel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(10, Short.MAX_VALUE))
                );

                sp1.setBackground(new java.awt.Color(225, 255, 255));
                sp1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Real Time Monitor Data", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
                sp1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
                sp1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

                tbl1.setBackground(new java.awt.Color(225, 255, 255));
                tbl1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                tbl1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                tbl1.setModel(new javax.swing.table.DefaultTableModel(
                    new Object [][] {},
                    new String [] {
                        "No.", "Building", "Room", "SensorID", "Model", "Reading", "Status"
                    }
                ));
                tbl1.setRowHeight(30);
                sp1.setViewportView(tbl1);

                // TABLE COLUMNS - Rebalanced for wide layout
                if (tbl1.getColumnModel().getColumnCount() > 0) {
                    tbl1.getColumnModel().getColumn(0).setMinWidth(40);
                    tbl1.getColumnModel().getColumn(0).setPreferredWidth(50);
                    tbl1.getColumnModel().getColumn(0).setMaxWidth(80);

                    tbl1.getColumnModel().getColumn(1).setMinWidth(150);
                    tbl1.getColumnModel().getColumn(1).setPreferredWidth(250);
                    tbl1.getColumnModel().getColumn(1).setMaxWidth(400);

                    tbl1.getColumnModel().getColumn(2).setMinWidth(150);
                    tbl1.getColumnModel().getColumn(2).setPreferredWidth(250);
                    tbl1.getColumnModel().getColumn(2).setMaxWidth(400);

                    tbl1.getColumnModel().getColumn(3).setMinWidth(100);
                    tbl1.getColumnModel().getColumn(3).setPreferredWidth(150);
                    tbl1.getColumnModel().getColumn(3).setMaxWidth(200);

                    tbl1.getColumnModel().getColumn(4).setMinWidth(80);
                    tbl1.getColumnModel().getColumn(4).setPreferredWidth(120);
                    tbl1.getColumnModel().getColumn(4).setMaxWidth(150);

                    tbl1.getColumnModel().getColumn(5).setMinWidth(80);
                    tbl1.getColumnModel().getColumn(5).setPreferredWidth(120);
                    tbl1.getColumnModel().getColumn(5).setMaxWidth(150);

                    tbl1.getColumnModel().getColumn(6).setMinWidth(100);
                    tbl1.getColumnModel().getColumn(6).setPreferredWidth(150);
                    tbl1.getColumnModel().getColumn(6).setMaxWidth(200);
                }

                sp2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
                sp2.setViewportBorder(javax.swing.BorderFactory.createTitledBorder(null, "Serial Monitor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

                txtSerialMonitor.setBackground(new java.awt.Color(225, 255, 255));
                txtSerialMonitor.setColumns(20);
                txtSerialMonitor.setRows(5);
                sp2.setViewportView(txtSerialMonitor);

                // MAIN CONTENT PANE LAYOUT (All 10px gaps)
                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sp1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1180, Short.MAX_VALUE)
                            .addComponent(pnl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnl3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sp2))
                        .addContainerGap())
                );
                layout.setVerticalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10) // 10px Pad
                        .addComponent(pnl1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10) // 10px Pad
                        .addComponent(pnl3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10) // 10px Pad
                        .addComponent(sp1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10) // 10px Pad
                        .addComponent(sp2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(10, Short.MAX_VALUE)) // 10px Pad
                );

                pack();
            }// </editor-fold>//GEN-END:initComponents
    private void txtUserIDActionPerformed(java.awt.event.ActionEvent evt) {
        // Handled by custom logic
    }

    private void tbtnStartStopActionPerformed(java.awt.event.ActionEvent evt) {
        tbtnStartStop.setFocusPainted(false);
        tbtnStartStop.setContentAreaFilled(false);
        tbtnStartStop.setOpaque(true);
        tbtnStartStop.setBackground(Color.WHITE); 

        if (tbtnStartStop.isSelected()) {
            /* System Running State */
            tbtnStartStop.setText("STOP SYSTEM");
            tbtnStartStop.setForeground(new Color(255, 0, 0));
            tbtnStartStop.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(255, 0, 0), 2));
            simulationTimer.start(); 
        } else {
            /* System Stopped State */
            tbtnStartStop.setText("START SYSTEM");
            tbtnStartStop.setForeground(new Color(63, 127, 0));
            tbtnStartStop.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(63, 127, 0), 2)); 
            simulationTimer.stop(); 
        }
    }

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {
        btnDelete.setFocusPainted(false);
        int row = tbl1.getSelectedRow();

        if (row != -1) {
            sensorList.remove(row);
            tableModel.removeRow(row);

            // Re-sequence the row numbers for visual continuity
            for (int i = 0; i < tableModel.getRowCount(); i++) {
                tableModel.setValueAt(i + 1, i, 0);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Select a row to delete!");
        }
    }

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {
        btnAdd.setFocusPainted(false);

        String currentID = txtSensorID.getText().trim();
        String selectedModel = cmbSensorModel.getSelectedItem().toString();

        // Automatically assign a system-generated ID if the field is empty
        if (currentID.isEmpty()) {
            currentID = generateNextSensorID(getPrefixForModel(selectedModel));
        }

        // Verify if the proposed ID already exists in the system
        boolean isDuplicate = false;
        for (SystemData.TemperatureSensor s : sensorList) {
            if (s.getId().equals(currentID)) {
                isDuplicate = true;
                break;
            }
        }

        if (isDuplicate) {
            String prefix = getPrefixForModel(selectedModel);
            if (currentID.contains("-")) {
                prefix = currentID.substring(0, currentID.lastIndexOf("-"));
            }

            // Generate the next available sequential ID for suggestion
            String suggestedID = generateNextSensorID(prefix);

            int choice = JOptionPane.showConfirmDialog(
                this, 
                "Duplicate Sensor ID \"" + currentID + "\"\nSave as \"" + suggestedID + "\"?", 
                "Duplicate Detected", 
                JOptionPane.OK_CANCEL_OPTION,
                JOptionPane.WARNING_MESSAGE
            );

            if (choice == JOptionPane.OK_OPTION) {
                // Proceed with the system-suggested ID
                currentID = suggestedID; 
            } else {
                // Halt the addition process and populate the text field with the suggestion
                txtSensorID.setText(suggestedID);
                return; 
            }
        }

        addSensorToSystem(
            txtLocation.getText(), 
            txtRoom.getText(), 
            currentID, 
            selectedModel
        );

        // Populate the field with the next sequential ID for subsequent entries
        txtSensorID.setText(generateNextSensorID(getPrefixForModel(selectedModel)));
        JOptionPane.showMessageDialog(this, "Sensor Added!");
    }

    private void tbtnEditSaveActionPerformed(java.awt.event.ActionEvent evt) {
        tbtnEditSave.setFocusPainted(false);

        if (tbtnEditSave.isSelected()) {
            /* Edit Mode Initialization */
            int row = tbl1.getSelectedRow();
            if (row == -1) {
                JOptionPane.showMessageDialog(this, "Please select a row to edit first!");
                tbtnEditSave.setSelected(false); 
                return;
            }

            tbtnEditSave.setContentAreaFilled(false); 
            tbtnEditSave.setOpaque(true);             
            tbtnEditSave.setBackground(Color.WHITE);  

            isEditMode = true;
            rowToEdit = row;

            tbtnEditSave.setText("Save");
            tbtnEditSave.setForeground(new Color(63, 127, 0));
            tbtnEditSave.setBorder(javax.swing.BorderFactory.createCompoundBorder(
                javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new Color(63, 127, 0)),
                javax.swing.BorderFactory.createEmptyBorder(3, 10, 3, 10)
            ));

            btnAdd.setEnabled(false); 
            btnDelete.setEnabled(false); 
            tbl1.setEnabled(false); 

        } else {
            /* Save Mode & Reversion to Default Layout */
            if (rowToEdit != -1) {
                SystemData.TemperatureSensor s = sensorList.get(rowToEdit);
                s.getRoom().getLocation().setName(txtLocation.getText());
                s.getRoom().setName(txtRoom.getText());
                s.setId(txtSensorID.getText());
                s.setModel(cmbSensorModel.getSelectedItem().toString());

                tableModel.setValueAt(txtLocation.getText(), rowToEdit, 1);
                tableModel.setValueAt(txtRoom.getText(), rowToEdit, 2);
                tableModel.setValueAt(txtSensorID.getText(), rowToEdit, 3);
                tableModel.setValueAt(cmbSensorModel.getSelectedItem(), rowToEdit, 4);
            }

            tbtnEditSave.setContentAreaFilled(true); 
            tbtnEditSave.setOpaque(true); 
            tbtnEditSave.setBackground(null);        

            isEditMode = false;
            rowToEdit = -1;

            tbtnEditSave.setText("Edit");
            tbtnEditSave.setForeground(Color.BLACK);
            tbtnEditSave.setBorder(javax.swing.UIManager.getBorder("Button.border")); 

            btnAdd.setEnabled(true); 
            btnDelete.setEnabled(true); 
            tbl1.setEnabled(true);
        }
    }

    private void txtSensorIDActionPerformed(java.awt.event.ActionEvent evt) {
        // Handled by custom logic
    }

    private void txtLocationActionPerformed(java.awt.event.ActionEvent evt) {
        // Handled by custom logic
    }

    private void txtRoomActionPerformed(java.awt.event.ActionEvent evt) {
        // Handled by custom logic
    }

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {
        btnClear.setFocusPainted(false);
        txtLocation.setText("");
        txtRoom.setText("");

        /* * Resetting the combo box index triggers the Action Listener, 
         * which automatically generates and populates the default sensor ID.
         */
        cmbSensorModel.setSelectedIndex(0); 
    }

    private void initCustomLogic() {
        tableModel = (DefaultTableModel) tbl1.getModel();

        simulationTimer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                // Retrieve and validate API credentials
                    // --- 1. GET TOKEN ---
                    String token = txtToken.getText().trim();
                    if (token.equals("Insert Chat Bot Token Keys (Get Token from BotFather)")) {
                        token = ""; // Safely sets it to blank instead of hardcoding a real key
                    }

                    // --- 2. GET USER ID ---
                    String uid = txtUserID.getText().trim();
                    if (uid.equals("Insert User ID (Get User ID from IDBot)")) {
                        uid = ""; // Safely sets it to blank
                    }

                SystemData.AlertSystem.setConfiguration(
                    token, 
                    uid, 
                    txtSerialMonitor
                );

                // Iterate through the backend object list to process new data
                for (int i = 0; i < sensorList.size(); i++) {
                    SystemData.TemperatureSensor s = sensorList.get(i);
                    s.updateData();
                    tableModel.setValueAt(s.getReading(), i, 5);
                    tableModel.setValueAt(s.getStatus(), i, 6);
                }
            }
        });

        // Event listener to regenerate IDs automatically upon model selection
        cmbSensorModel.addActionListener(e -> {
            if (!isEditMode) {
                String selectedModel = cmbSensorModel.getSelectedItem().toString();
                String prefix = getPrefixForModel(selectedModel);
                txtSensorID.setText(generateNextSensorID(prefix));
            }
        });

        // Transfers selected table data to the configuration interface for editing
        tbl1.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting() && tbl1.getSelectedRow() != -1 && !isEditMode) {
                int row = tbl1.getSelectedRow();

                txtLocation.setText(getSafeString(row, 1));
                txtRoom.setText(getSafeString(row, 2));
                txtSensorID.setText(getSafeString(row, 3));

                String modelVal = getSafeString(row, 4);
                if (!modelVal.isEmpty()) {
                    cmbSensorModel.setSelectedItem(modelVal);
                }
            }
        });

        // Ensure the Sensor ID field remains editable for manual entry
        txtSensorID.setEditable(true);

        // Preload default system configurations upon launch
        String firstModel = "BME280";
        cmbSensorModel.setSelectedItem(firstModel);
        String firstID = generateNextSensorID(getPrefixForModel(firstModel));
        addSensorToSystem("FKTEN Block 8", "Computer Lab", firstID, firstModel);

        txtSensorID.setText(generateNextSensorID(getPrefixForModel(firstModel)));
    }

    /**
     * Determines the appropriate ID prefix based on the selected sensor model.
     * @param model The selected sensor model.
     * @return The corresponding string prefix.
     */
    private String getPrefixForModel(String model) {
        if (model.equals("Unspecified")) {
            return "TT"; 
        }
        return model; 
    }

    /**
     * Generates the next available sequential ID based on a specific prefix.
     * @param prefix The alphanumeric string preceding the numerical ID.
     * @return A formatted, unique ID string.
     */
    private String generateNextSensorID(String prefix) {
        int testNum = 1;
        while (true) {
            String testID = String.format("%s-%03d", prefix, testNum);
            boolean exists = false;

            for (SystemData.TemperatureSensor s : sensorList) {
                if (s.getId().equals(testID)) {
                    exists = true;
                    break;
                }
            }

            if (!exists) {
                return testID;
            }

            testNum++;
        }
    }

    /**
     * Retrieves table cell data safely to prevent NullPointerExceptions.
     */
    private String getSafeString(int row, int col) {
        Object val = tableModel.getValueAt(row, col);
        if (val == null) {
            return ""; 
        }
        return val.toString();
    }

    /**
     * Adds a newly constructed sensor to both the logic layer and the GUI table.
     */
    private void addSensorToSystem(String loc, String room, String id, String model) {
        SystemData.TemperatureSensor s = new SystemData.TemperatureSensor(loc, room, id, model);
        sensorList.add(s);
        tableModel.addRow(new Object[]{
            tableModel.getRowCount() + 1, loc, room, id, model, "-------", "Offline"
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JComboBox<String> cmbSensorModel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel pnl1;
    private javax.swing.JPanel pnl2;
    private javax.swing.JPanel pnl3;
    private javax.swing.JScrollPane sp1;
    private javax.swing.JScrollPane sp2;
    private javax.swing.JTable tbl1;
    private javax.swing.JToggleButton tbtnEditSave;
    private javax.swing.JToggleButton tbtnStartStop;
    private javax.swing.JTextField txtLocation;
    private javax.swing.JTextField txtRoom;
    private javax.swing.JTextField txtSensorID;
    private javax.swing.JTextArea txtSerialMonitor;
    private javax.swing.JTextField txtToken;
    private javax.swing.JTextField txtUserID;
    // End of variables declaration//GEN-END:variables
}